advertisement.daangn.com
daangn/websites pull request #256
Opened 2021-09-13 06:25 UTC by CXZ7720

2021-09-13 07:09 UTC, cometkim requested changes

2021-09-13 07:09 UTC, cometkim commented on advertisement.daangn.com/src/components/molecules/ArrowLink.tsx
> +  }
태그매니저 초대드릴께요 트래킹 코드 제거해주시면 감사

2021-09-13 07:56 UTC, CXZ7720 commented on advertisement.daangn.com/src/components/molecules/ArrowLink.tsx
> +  }
aaron@daangn.com 이에요! 감사합니당 :)

2021-09-13 08:52 UTC, cometkim requested changes
참고로 gatsby-theme-website 상속하시면 Header Footer 그대로 사용하실 수 있어요

2021-09-13 08:52 UTC, cometkim commented on advertisement.daangn.com/src/components/organisms/DownloadBtnMobile.tsx
> +    else window.open("https://www.daangn.com/", "_blank"); // userAgent 가 판명되지 않은 기타 경우 당근 홈페이지로 리다이렉트
이게 default 동작같은데요. appsflyer onelink 하나 발급해서 쓰시는게 좋지 않을까요?

2021-09-13 08:55 UTC, cometkim commented
페어 필요하면 언제든지 요청주셔용.

2021-09-14 01:23 UTC, CXZ7720 commented on advertisement.daangn.com/src/components/organisms/DownloadBtnMobile.tsx
> +    else window.open("https://www.daangn.com/", "_blank"); // userAgent 가 판명되지 않은 기타 경우 당근 홈페이지로 리다이렉트
안녕하세요 팀! AppsFlyerOneLink 이용해서 교체완료했어요
https://github.com/daangn/websites/pull/256/commits/56205c6a05d729f2ba180e18dbc60b18677f2a55#

2021-09-14 01:24 UTC, CXZ7720 commented on advertisement.daangn.com/src/components/molecules/ArrowLink.tsx
> +  }
태그매니저를 이용해서 추적하도록 바꾸고 기존 코드는 걷어냈어요

https://github.com/daangn/websites/pull/256/commits/0c955f8476000c30eb8dfe632a02d604a0b5dae0
https://github.com/daangn/websites/pull/256/commits/50ecf01e1e9980b5cfab281d0589f65678e40bfa
https://github.com/daangn/websites/pull/256/commits/b4e5071670af955816b0c549f99de034842dab17

2021-09-17 08:45 UTC, merged