feat(team.daangn.com): 채용 공고 목록 상단 배너
daangn/websites pull request #383
Opened 2021-12-01 04:06 UTC by tonyfromundefined

2021-12-02 13:01 UTC, tonyfromundefined commented
<img width="885" alt="스크린샷 2021-12-02 오후 10 00 29" src="https://user-images.githubusercontent.com/20325202/144426920-27dc6ef0-4575-4963-ada5-ceda659c65ad.png">

2021-12-02 13:06 UTC, tonyfromundefined commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobsPage.tsx
> +    marginTop: '-5rem',
- 상단바에 marginBottom이 잡혀있어서 이걸 빼면 전부 바꿔줘야 하더라구요. 그래서 minus margin을 썼어요.
- 상단바에 margin 거는거보다는 공통 title 영역에 marginTop을 거는게 더 좋을거같은데... 손대기가 애매해서 놔뒀어요.

2021-12-02 13:07 UTC, tonyfromundefined commented on _packages/@karrotmarket/prismic-config/schema/team_banner.json
> +}
- 자동으로 안되서 prismic에서 손으로 복붙했어요. 스타일이 다르던데... (`:`가 떨어져있음) 한번 확인해주세요

2021-12-02 13:26 UTC, cometkim requested changes
일단 코드 전에 바로 눈에 띄이는 부분 부터 잡아보죵

- image alt 가 없어요
- 네이티브 `<img>` 대신 Gatsby Image 를 써주세요!

2021-12-02 13:30 UTC, cometkim requested changes

2021-12-02 13:30 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobsPage.tsx
> +      {data.prismicTeamBanner?.data?.left?.url && data.prismicTeamBanner.data?.right?.url && (
이건 page data 에 포함시키지말고 `team.daangn.com` 에서만 static data 로 뽑아 쓰는게 더 좋을거같아요.

2021-12-02 13:30 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobsPage.tsx
> +
native img 대신 Gatsby Image 로 변경

2021-12-02 13:30 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobsPage.tsx
> +const BannerArea = styled('div', {
의미론적으로 aside 쯤 될거같은데.. 일단 요건 킵하시죵

2021-12-02 13:30 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobsPage.tsx
> +    marginTop: '-5rem',
음 그러네요 내가 여기 margin bottom 왜 잡아놨더라... 기억이 정확히는 안나지만 지금보면 말씀하신 방향이 맞는듯

2021-12-02 15:13 UTC, cometkim requested changes

2021-12-02 15:13 UTC, cometkim commented on team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobsPage/BannerArea.tsx
> +        <BannerImg image={banner.left.gatsbyImageData as any} alt={banner.left.alt ?? 'banner 1'} />
한국 전용 + ad-hoc 이벤트니까 더 친절하게 나가도 될거같아요~

것보다 아싸리 저는 alt 안적으면 안그려야 한다고 봅니다

2021-12-02 15:15 UTC, tonyfromundefined commented on team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobsPage/BannerArea.tsx
> +        <BannerImg image={banner.left.gatsbyImageData as any} alt={banner.left.alt ?? 'banner 1'} />
굿 안 그리는쪽으로 갑니다

2021-12-02 17:17 UTC, cometkim requested changes

2021-12-02 17:17 UTC, cometkim commented on team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobsPage/BannerArea.tsx
> +  }
이건 좀 말이 안되네요 wont fix

```suggestion
```

2021-12-02 17:24 UTC, cometkim commented
![image](https://user-images.githubusercontent.com/9696352/144472077-e88e09d4-708c-40ef-a397-aaea0ecaa796.png)
이래서 중간 브레이크를 포인트 잘 활용해야합니다. pc/mobile 구분은 어림도 없어요

2021-12-02 17:42 UTC, cometkim commented
@tonyfromundefined 

일단 코드는 고쳐놨는데요. localFile.childImageSharp 가 null 로 잡히고 있을거에요.

왜냐면 svg 를 업로드하셔서 mimeType 이 text/svg+xml 로 들어가기 때문인데요. 어차피 Gatsby Image 로 레스터라이즈해서 쓰일 부분이면 업로드도 png/jpeg 를 해주셔야하고, 진짜 SVG 컨텐츠를 쓰고 싶은거라면 리치텍스트(코드블럭) 폼을 만드셔야해요

2021-12-03 02:53 UTC, tonyfromundefined commented on team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobsPage/BannerArea.tsx
> +  }
디자인 스펙에서 배너 노출시에 타이틀이 없는걸로 나와서 숨겨놓았어요.

https://www.figma.com/file/LO3Ohg2tqZ5MFcq19K5Tmh/%EC%B1%84%EC%9A%A9?node-id=2073%3A3397

존중해야드려야 하지 않을까요?

2021-12-03 05:05 UTC, cometkim commented on team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobsPage/BannerArea.tsx
> +  }
디자인 피드백을 드리는게 맞을거같아요

2021-12-03 05:09 UTC, cometkim commented on team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobsPage/BannerArea.tsx
> +  }
레퍼런스로 참고하세요: https://developers.google.com/search/mobile-sites/mobile-first-indexing#content-is-same

2021-12-03 08:29 UTC, tonyfromundefined commented
- 이미지가 깨지는 문제가 생겨서 수정했어요~
<img width="1115" alt="스크린샷 2021-12-03 오후 5 28 07" src="https://user-images.githubusercontent.com/20325202/144570328-ec92fc63-5be2-4bd8-aef0-2f4db86622b2.png">

- 그리고 breakpoint가 `@lg` -> `@md`가 더 적절할거같아서 교체했어요.
<img width="1000" alt="스크린샷 2021-12-03 오후 5 28 45" src="https://user-images.githubusercontent.com/20325202/144570366-9889b044-3273-4207-8c12-63b28b65b644.png">

2021-12-03 11:13 UTC, cometkim approved these changes
굳

![image](https://user-images.githubusercontent.com/9696352/144593342-b4969bc7-aeb1-4315-8f64-3f7b6c2a12ef.png)

2021-12-03 11:21 UTC, cometkim commented
traced svg 가 좀 더 낫네요 글자들이 다 뚜렷해서

![Sizzy- localhost8000 03Dec 20 21](https://user-images.githubusercontent.com/9696352/144594376-e00f7bac-6607-4dfe-8c8d-8ab738843a7f.gif)

2021-12-03 11:28 UTC, merged

2021-12-03 12:59 UTC, cometkim commented
Resolves https://karrot.atlassian.net/browse/THRD-1