feat(team.daangn.com): 자주 묻는 질문 구조 변경
daangn/websites pull request #555
Opened 2022-03-27 18:12 UTC by ginger-kang

[WMAS-36](https://karrot.atlassian.net/jira/software/projects/WMAS/boards/185?selectedIssue=WMAS-36)

자주 묻는 질문 그룹화 작업 했어요.
- `FaqPage`로 각 그룹들 페이지 생성했고, `FaqList`에서 검색된 컨텐츠들 보여주게끔 했어요!
- 이전에 말씀드린거 검색에서 `ref`를 `question`으로 잡았어요.

2022-03-28 06:02 UTC, cometkim requested changes

2022-03-28 06:02 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +              {faq.faq_page.uid.replace(/\-/, ' ')}
uid 를 label 로 쓰면 안되죠..

2022-03-28 06:02 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +  }
이거 함수 선언하는 의미 있나요

2022-03-28 06:02 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +  const searchResults = useFaqSearch(searchQuery);
FAQ가 검색 인덱스가 왜 필요한가요. 지금 구조면 그냥 페이지 데이터 직접 필터하는게 더 빠른거 아닌가요.

2022-03-28 06:02 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobPostPage.tsx
> +          to="/faq/지원-관련/"
하드코딩 하지 말아주세요. 컨텐츠는 언제든지 변경될 수 있습니다.

2022-03-28 06:02 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/utils/useFaqSearch.tsx
> +export const useFaqSearch = (query?: string) => {
왜 필요한지 의문...

2022-03-28 06:05 UTC, cometkim commented
FAQ 에 검색기능 반드시 들어가는지 확인해보고
필요하다면 유효한 구조적인 적용은 둘 중 하나인데

1. 카테고리 내에서 빠른 필터
2. 전체 카테고리 상에서 빠른 브라우징

전자라면 별도 인덱스가 따로 필요하지 않아보이고요 (페이지 데이터 자체가 이미 인덱스 역할을 수행함)
후자라면 컨텐츠 네비게이션보다 상위 맥락으로 구분되어야 할 것 같은데 제목 구조랑 썩 잘맞지 않아서 고민이 필요해보여요

2022-03-28 06:10 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/gatsby/gatsby-node.ts
> +      }
> 이러면 링크와 상관없이 전체 FAQ 컨텐츠를 다 가져올텐데 team.daangn.com 이랑 상관 없는 컨텐츠도 포함될 수 있어요

위에서 `entries`의 id를 받아오면 각 그룹 페이지의 `prismicFaq` id와 달라서, 이걸 넘겨주기 위해서 따로 쿼리 날렸었어요. 위의 경우를 생각 못했어요.. `prismicTeamContents`의 `faq_entries` -> `document`로 접근하는게 좋겠네요!

2022-03-28 06:11 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/gatsby/gatsby-node.ts
> +      }
어떤식으로 하시던 적어도 필터는 필요합니다. 근데 그냥 linked document 직접 쓰시는게 좋아보이고요

2022-03-28 06:12 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +              {faq.faq_page.uid.replace(/\-/, ' ')}
네넵ㅠ 따로 보여줄 label명을 만들어서 그걸 쓰도록 할게요

2022-03-28 06:12 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +              {faq.faq_page.uid.replace(/\-/, ' ')}
왜 제목 이외의 label 이 따로 필요한가요?

2022-03-28 06:13 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +              {faq.faq_page.uid.replace(/\-/, ' ')}
제목 그대로 들어가나요? 저는 지금 제목이 단순히 길다고 느껴져서 그런거긴 해요.

2022-03-28 06:14 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +  const searchResults = useFaqSearch(searchQuery);
넵 이거 밑에 남겨주신 커멘트대로 여쭤보고 고민해볼게요!

2022-03-28 06:15 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +              {faq.faq_page.uid.replace(/\-/, ' ')}
목은 제목이고 길고 짧은건 직접 조절하실 일이긴 한데요. 정 navigation label 이 필요하다면 document 가 아니라 link 쪽에 추가해주세요.

2022-03-28 06:27 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +              {faq.faq_page.uid.replace(/\-/, ' ')}
> 정 navigation label 이 필요하다면 document 가 아니라 link 쪽에 추가해주세요.

음..지금 결국에 faq document를 링크하고 있는 걸로 알고 있는데, document가 아니라 link쪽에 추가하는게 무슨말인지 잘 이해가 안돼요. document내에서 label을 추가하는게 아니라 아래 이미지(faq link쪽)에서 추가하라는 말씀이신가요?? 
이거 설명 좀만 더 부탁드려도 될까요..?

<img width="980" alt="image" src="https://user-images.githubusercontent.com/62840502/160338770-512799da-70bb-4a9e-acac-2f5050ab55bb.png">

2022-03-28 06:38 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +              {faq.faq_page.uid.replace(/\-/, ' ')}
엇 이거 확인했어요!

2022-03-28 06:40 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +              {faq.faq_page.uid.replace(/\-/, ' ')}
label 필요할 경우 말씀하신대로 해볼게요~

2022-03-31 08:00 UTC, cometkim requested changes

2022-03-31 08:00 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +    navigate(`?q=${encodeURIComponent(searchInput)}`)
이거 근데 submit 보다 change + transition 쓰는게 적절하지 않을까용

2022-03-31 08:00 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +import queryString from 'query-string'
use native `URLSearchParams`

2022-03-31 08:00 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +import { ReactComponent as SearchdSvg } from '../assets/searchOutlineM.svg';
use file-loader

2022-04-04 07:42 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +    navigate(`?q=${encodeURIComponent(searchInput)}`)
음 검색 결과가 url 쿼리에서 가져와서 쓰는 방식이다보니까, submit이 좀 더 자연스러울 것 같아요!

2022-04-04 07:43 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/gatsby/gatsby-node.ts
> +      actions.createPage({
이거 잘 이해를 못했는데, 위에서 엔트리 length 체크해서 내용이 없을 경우 페이지를 아예 생성하지 않고 있어요.
여기서 각 엔트리마다 내용을 한번 더 필터 걸어서 컨텐츠가 있는지 확인하라는 말씀이신가여??

2022-04-04 07:45 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +import { ReactComponent as SearchdSvg } from '../assets/searchOutlineM.svg';
기존 jobs에 있는 search를 재활용해서 쓰고 있어서 일단 배포 나가고 추후 작업으로 해도 될 것 같은데 어떠신가용

2022-04-05 07:59 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/gatsby/gatsby-node.ts
> +      actions.createPage({
네네 CMS에 제한이 없기 때문에 빈 엔트리가 생성될 수 있어서요. 내용이나 제목이 없으면 FAQ 로써 아무 의미가 없어요

2022-04-06 06:31 UTC, cometkim requested changes
1. FAQ 컨텐츠 크기 전반적으로 키우기
2. gatsby-node 에서 FAQ 페이지 생성 전에 컨텐츠 밸리데이션 & 가드 하기
3. `/faq/` 페이지 리다이렉션 동작 제대로 안되는 거 트러블슈팅
4. 카테고리 선택 `<Link>` 로 처리하기
5. 검색바 입력 시 한글 컴포지션 풀리는 버그 해결
6. 검색 조건을 onChange transition 으로 변경해서 다른 곳이랑 동작 일관성 맞추기

2022-04-08 10:28 UTC, ginger-kang commented
faq컨텐츠 보여주는 아코디언 메뉴 크기 키워놨고, 4, 5, 6까지 리뷰 반영해놨어요!
2번에서, 링크된 document에 entries가 아무것도 없을 때를 일단 걸어놨어요.(link는 되어 있는데, link document자체에 컨텐츠가 없을 경우)
이렇게 한 이유가 각 컨텐츠를 확인해서 validate하게 되면, 다른 컨텐츠는 다 있는데 빈 컨텐츠가 들어있다고해서 페이지 자체를 생성하지 않는건 아닌 것 같아서에요~ 지금처럼 link document만 체크하고, document의 각 개별 컨텐츠는 아코디언에서 보여줄 때 안보여주면 될 것 같아요!

2022-04-12 09:04 UTC, cometkim requested changes

2022-04-12 09:04 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +  const searchParams = new URLSearchParams(location.search);
```suggestion
  const searchParams = new URLSearchParams(location.search);
```

이건 useSyncExternalStore 써서 동기화 및 서버 폴백 처리가 명시적으로 되어야 안전할 것 같습니다.

2022-04-12 09:04 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/components/FaqList.tsx
> +  data: GatsbyTypes.TeamWebsite_FaqList_faqListFragment,
`{namespace}_{componentName}_{propName}` 컨벤션 쓰고 있어요 (릴레이와 동일)

2022-04-12 09:08 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
> +  const searchParams = new URLSearchParams(location.search);
오.. `useSyncExternalStore` 처음 알았네요ㅋㅋㅋ 👍

2022-04-13 08:04 UTC, cometkim commented
이거 일단 병합하고 제가 다음주쯤에? 후속작업 할게요

- 동기화 느릴 때 search 가 URL 이랑 싱크 안되는 현상
- svg 에셋 로더
- 짜잘한 컨벤션들

2022-04-13 08:04 UTC, merged