feat: migrate seed design
daangn/websites pull request #577
Opened 2022-04-28 15:12 UTC by ginger-kang

team.daangn.com에 seed design 적용시키는 작업했어요.

일단 `prefer-color-scheme` 기준으로 동작하고, 원래는 `uSES`로 뺐었는데 스크립트로 변경해서 넣어놨어요.
`color`쪽만 다 적용시켜놨고 `font`나 다른 stitches theme은 그대로 둔 상태에요.

dark color일 때 잘 안보이는 것 같아서 `form`, `input`들에 대해 토큰 값을 재정의할 필요도 있을 것 같아요.
의견 주시면 감사하겠습니당

2022-05-04 10:53 UTC, cometkim requested changes
Q. 소셜 서비스들 아이콘 소스 바꾸신거 어디서 가져온거에요..?

2022-05-04 10:53 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-global-website/package.json
> +    "@seed-design/stylesheet": "^1.0.0-alpha.0",
버전이 달라요! alpha 채널로 받는게 좋을 거 같아요

```suggestion
    "@seed-design/design-token": "alpha",
    "@seed-design/stylesheet": "alpha",
```

2022-05-04 10:53 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/package.json
> +    "@karrotmarket/design-token": "^1.1.2",
이거 불필요해요 (Renovate 가 관리함)

2022-05-04 10:53 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/package.json
> +    "@seed-design/design-token": "^1.0.0-alpha.0",
```suggestion
    "@seed-design/design-token": "alpha",
```

2022-05-04 10:53 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/components/ArrowLink.tsx
> +import { ReactComponent as ArrowSvg } from './arrowLink/arrow.svg'
음... 아무래도 SVG 시트를 빨리 만들어야 할 거 같아요.

이거 반복적으로 등장하는 녀석이라 크리티컬패스 마크업 사이즈가 엄청나게 커질거에요

2022-05-04 10:53 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/layouts/DefaultLayout.tsx
> +          data-seed="light dark"
이거 딱히 포맷이 있진 않아요 ㅋㅋㅋㅋㅋ

```suggestion
          data-seed
```

2022-05-04 10:53 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-website/package.json
> +    "@seed-design/design-token": "^1.0.0-alpha.0",
```suggestion
    "@seed-design/design-token": "alpha",
```

2022-05-04 11:26 UTC, ginger-kang commented
> Q. 소셜 서비스들 아이콘 소스 바꾸신거 어디서 가져온거에요..?

따로 안가져오고 이전에 file-loader로 가져오고 있던거 리액트 컴포넌트로 바꾸고 fill로 채워주게 했어용

2022-05-04 11:27 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-global-website/package.json
> +    "@seed-design/stylesheet": "^1.0.0-alpha.0",
아하 변경해놓을게요~!

2022-05-04 11:28 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/package.json
> +    "@karrotmarket/design-token": "^1.1.2",
구웃

2022-05-04 11:28 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/components/ArrowLink.tsx
> +import { ReactComponent as ArrowSvg } from './arrowLink/arrow.svg'
👍

2022-05-04 11:29 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-theme-team-website/src/layouts/DefaultLayout.tsx
> +          data-seed="light dark"
아하 일단 가이드 보고 해놨었는데 없군요ㅋㅋㅋ

2022-05-09 10:16 UTC, ginger-kang commented
흠.. 이거 팀당근 clean build돌려도 잘 돌아가는데 gatsby cloud에서 fail먹이는군요

2022-05-09 19:57 UTC, cometkim approved these changes
수고하셧습니다.

2022-05-09 19:58 UTC, merged