[WMAS-42] eperate corporation
daangn/websites pull request #593
Opened 2022-05-18 13:36 UTC by ginger-kang

법인 별 분리작업!

**team.daangn.com**
당근마켓: `/jobs/당근마켓/`, `/jobs/당근마켓/department/`
당근페이: `/jobs/당근페이/`, `/jobs/당근페이/department/`

**글로벌**
당근마켓: `/jobs/karrot/`, `/jobs/karrot/department/`

기존 `JobPost`에서 `enum`타입으로 받고 있다보니 전체 필터할 때 한계가 있어 커스텀 타입을 만들었어요.
전체 법인은 그대로 `/jobs/` 유지하고, `jobPost`에서는 안넣는게 좋을 것 같아 법인을 url에 안넣어줬어요.
모바일에선 [피그마](https://www.figma.com/file/LO3Ohg2tqZ5MFcq19K5Tmh/%EC%B1%84%EC%9A%A9?node-id=121%3A268) 대로 고용형태가 보이지 않게 했어요.

2022-05-19 03:19 UTC, ginger-kang commented
후.. `AllLokaliseMessages`

2022-05-19 06:08 UTC, cometkim commented
> 후.. AllLokaliseMessages

이건 고쳐놨어요

2022-05-19 06:09 UTC, cometkim requested changes
corp 필터 따로 페이지 만들지 마시고 그냥 query string 으로 클라이언트에서 필터링 해주세요.

2022-05-19 06:11 UTC, ginger-kang commented
> query string 으로 클라이언트에서 필터링

@cometkim 음.. 혹시 query string으로 하는 이유가 있을까용?

2022-05-19 06:19 UTC, cometkim commented
> 음.. 혹시 query string으로 하는 이유가 있을까용?

URL pathname 은 구조적인 표현을 못해요. 같은 계층에서 두가지 관심사(department, corp)를 다루면서부터 구조적인 문제가 생길 수 있어요. 요컨데 같은 계층의 역할을 추론하기 어려워져요.

URL에 "당근마켓" 을 Persist 하는 것 만으로는 컨텐츠 퀄리티에 영향을 줄 수 없어요. department 필터의 경우 목록의 항목들의 "제목"에 따라 느슨한 연결을 주장할 수 있지만, corp는 주요한 컨텐츠에 영향을 주지 못하기 때문에 무수히 많은 중복 페이지를 만들 뿐이에요.

네트워크 페이로드 관점에서도 그리 좋지 않아요. 단순 계산 했을 때 공고 목록 페이지 수가 3배가 될 텐데 그만큼 캐시히트가 떨어진다고 봐요.

2022-05-19 08:42 UTC, ginger-kang commented
>URL pathname 은 구조적인 표현을 못해요. 같은 계층에서 두가지 관심사(department, corp)를 다루면서부터 구조적인 문제가 생길 수 있어요. 요컨데 같은 계층의 역할을 추론하기 어려워져요.
>
> URL에 "당근마켓" 을 Persist 하는 것 만으로는 컨텐츠 퀄리티에 영향을 줄 수 없어요. department 필터의 경우 목록의 항목들의 "제목"에 따라 느슨한 연결을 주장할 수 있지만, corp는 주요한 컨텐츠에 영향을 주지 못하기 때문에 무수히 많은 중복 페이지를 만들 뿐이에요.
>
> 네트워크 페이로드 관점에서도 그리 좋지 않아요. 단순 계산 했을 때 공고 목록 페이지 수가 3배가 될 텐데 그만큼 캐시히트가 떨어진다고 봐요.

@cometkim 
URL pathname이 구조적 표현을 못한다는게 이해가 잘 안가요. 혹시 팀이 말하시는 '계층'을 잘못 이해하고 있을 수도 있는데, corp가 department 보다 상위 계층이기도 하고 현재 두 가지 관심사를 다루고 있다보니까 해당 pr처럼 pathname에서 계층을 나누는게 좋을 것 같다고 생각했어요.
컨텐츠 퀄리티에 주는 영향은 생각을 못해봤네요. 팀이 말하신대로 주요 컨텐츠에는 영향을 못주겠네요.. 확실히 그에 따라 중복 페이지가 만들어 지겠군요..!
페이지 수가 늘어나는 건 맞긴 하지만, 채용 공고라는 특성상 많은 양이 아니기 때문에 괜찮다고 생각했었어요. 비슷한 맥락으로 공고를 보는 분들이 여러 직군들을 거쳐가면서 확인하지 않기 때문에 괜찮지 않을까요??

2022-05-19 08:44 UTC, cometkim commented
> URL pathname이 구조적 표현을 못한다는게 이해가 잘 안가요. 혹시 팀이 말하시는 '계층'을 잘못 이해하고 있을 수도 있는데, corp가 department 보다 상위 계층이기도 하고 현재 두 가지 관심사를 다루고 있다보니까 해당 pr처럼 pathname에서 계층을 나누는게 좋을 것 같다고 생각했어요.

음 쉽게 예시를 들어 표현하자면, `/jobs/karrot` 의 karrot 이 corp 인지 department 인지 모호하기 때문에 계속 ad-hoc 룰을 추가하는 방법으로 확장될 수 밖에 없다는거에요.

2022-05-19 08:59 UTC, ginger-kang commented
> 음 쉽게 예시를 들어 표현하자면, /jobs/karrot 의 karrot 이 corp 인지 department 인지 모호하기 때문에 계속 ad-hoc 룰을 추가하는 방법으로 확장될 수 밖에 없다는거에요.

@cometkim 아하..! 근데 `/jobs/karrot/department`로 pathname에서 표현하게 되면 모호한게 사라지지 않나요?

2022-05-19 08:59 UTC, ginger-kang commented
아 `/corp/`로 가야 말이 되나..

2022-05-19 09:11 UTC, ginger-kang commented
`/jobs/engineering-frontend/?corp=karrot`
`/jobs/karrot/engineering-frontend/`

2022-05-19 09:12 UTC, ginger-kang commented
@cometkim 음 이거 query string으로 작업해서 이따가 리뷰 요청드릴게요!

2022-05-20 02:30 UTC, cometkim commented on _packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobsPage.tsx
> +    : corp.enSlug === searchParams.get('corp'))
왜 language 에 따라 기능이 달라지나요...?

2022-05-20 02:30 UTC, cometkim commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
이게 왜 필요한가요....?

2022-05-20 02:34 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
@cometkim ko에선 `당근마켓`, en, jp에서 `karrot`으로 주려고 넣어놨어요.
통일하면 사실 필요없긴한데 나눠야 할 것 같아서요

2022-05-20 02:35 UTC, cometkim commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
로케일 하드코딩해서 기능 플래그로 쓰지 마세요.

데이터 구조가 바뀔 필요도 없는 것 같아요.

2022-05-20 02:38 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
음.. 그럼 query params에 `KARROT_MARKET`, `KARROT_PAY` enum값 그대로 통일해서 쓰는게 좋을까용?

2022-05-20 02:38 UTC, cometkim commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
그래도 되고 label 처럼 매핑해도 되고

2022-05-20 02:45 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
label로 하는건 결국 '당근마켓'이나 'Karrot'을 하드코딩으로 넣어야하지 않나요..?

2022-05-20 02:46 UTC, cometkim commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
그건 i18n 메시지라서 괜찮아요

2022-05-20 02:46 UTC, cometkim commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
그리고 쿼리스트링에 그렇게 할 필요는 없어요 그냥 enum 값 그대로 써도 돼요

2022-05-20 02:48 UTC, ginger-kang commented on _packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
> +  enSlug: string
🙆‍♂️

2022-05-20 06:28 UTC, ginger-kang commented
@cometkim 글로벌 채용사이트 쪽에 쿼리 응답이 안오는데 혹시 이유 아시나용?

2022-05-20 10:09 UTC, cometkim commented
> @cometkim 글로벌 채용사이트 쪽에 쿼리 응답이 안오는데 혹시 이유 아시나용?

쿼리 응답....?

2022-05-20 10:12 UTC, ginger-kang commented
@cometkim 
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/62840502/169506534-25d625f3-17fc-4c02-b9cb-129c935b4c61.png">
데이터가 안들어가있어서요~

2022-05-20 10:12 UTC, cometkim commented
이게 non-null 이 아니였다니

2022-05-20 10:13 UTC, cometkim commented
체크아웃해서 확인해볼게용~

2022-05-23 11:15 UTC, cometkim commented
@ginger-kang 재 현 이 안 되는데용..

2022-05-23 11:18 UTC, ginger-kang commented
@cometkim 
엇 안되시나용..? 저도 글로벌 쪽은 greenhouse 키가 없어서 디버깅을 못해서요ㅠ
preview에서 확인한건데, gatsby cloud 쪽 이슈일까요??

2022-05-23 11:18 UTC, cometkim commented
일단 암거나 푸시 해볼게용

2022-05-23 11:19 UTC, ginger-kang commented
네넵~

2022-05-23 11:43 UTC, ginger-kang commented
@cometkim 어라 글로벌 쪽 데이터 잘 들어있네요
ads랑 us도 clean빌드 잘 돌아가는데 터지네용ㅠ

2022-05-24 05:57 UTC, cometkim commented
일단 독립적인 이슈인 것으로,.,...

2022-05-24 06:00 UTC, ginger-kang commented
@cometkim 네네 그런것 같네요.. cloud 쪽에서 발생하는 이슈같아여
아니면 그린하우스 쪽 이슈일 가능성도 있을까요?

2022-05-24 06:39 UTC, cometkim commented
> 아니면 그린하우스 쪽 이슈일 가능성도 있을까요?

없다고 생각합니다.

2022-05-24 06:40 UTC, cometkim requested changes
<img width="357" alt="image" src="https://user-images.githubusercontent.com/9696352/169965197-d2482337-f116-4974-a187-d053c53c21b6.png">
이쪽 그리드 레이아웃 템플릿 수정이 안된것 같아요

2022-05-24 06:41 UTC, cometkim commented
> 이쪽 그리드 레이아웃 템플릿 수정이 안된것 같아요

엇 아니네

2022-05-24 06:42 UTC, cometkim commented
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/9696352/169965405-2f6c4da1-b520-47a6-bb37-e89156ca231b.png">

직군이랑 법인이랑 위치만 바꿀 수 있을까요. 왜 들쭉날쭉 한가 생각해봤는데 직군이 실제로 커서 그렇네요

2022-05-24 07:39 UTC, ginger-kang commented
> 직군이랑 법인이랑 위치만 바꿀 수 있을까요.

@cometkim 수정해놨어요~

2022-05-24 09:11 UTC, cometkim approved these changes
감솨감솨

2022-05-24 09:12 UTC, merged

2022-05-24 09:58 UTC, cometkim commented
Resolved [WMAS-42]